#!/usr/bin/env ruby

# A console application to display Ruby HTML documentation.

require 'optparse'
require_relative '../lib/webri/version'
require_relative '../lib/webri'
require_relative '../lib/scraper'

NAME = <<EOT

Name:

There are four types of names, as determined by prefixes:

- Class or module: starts with a capital letter; e.g., 'Array'.
- Singleton method: starts with '::'; e.g., '::new'.
- Instance method: starts with '#' (escaped as '\\#', if your shell requires it);
  e.g., '#inspect'.
- Ruby file: starts with 'ruby:'; e.g., 'ruby:syntax_rdoc'.

Name handling:

- If name is a complete name of its type (and not also the start of other such names),
  webri opens the page for that name.
- If name is incomplete, but is the start of only one name of its type,
  webri asks whether to open the page for that name.
- If name is incomplete, but is the start of multiple names of its type,
  webri displays those names and lets you choose.
- If name is not a valid name of its type, webri asks whether show such names.
- If name is not valid at all (i.e., does not start with any of the prefixes above),
  webri prints an error message.

EOT
options = {}

parser = OptionParser.new

parser.version = WebRI::VERSION
parser.banner = <<-BANNER
webri is a console application for displaying Ruby online HTML documentation.
Documentation pages are opened in the default web browser.

Usage: #{parser.program_name} [options] name

BANNER

RELEASES = Scraper.scrapers.keys.inspect

parser.separator("Options:")
release_description = <<-EOT

EOT
parser.on('-r', '--release RELEASE',
          "Specify documentation release (one of #{RELEASES}).") do |value|
  options[:release_name] = value
end
parser.on('-i', '--info', 'Print information about webri.') do
  options[:info] = true
end
parser.on('--noreline', 'Do not use Reline (useful for testing).') do |value|
  options[:noreline] = true
end
parser.on('-n', '--noop', 'Do not actually open web pages.') do |value|
  options[:noop] = true
end
parser.on('-h', '--help', 'Print this help.') do
  puts parser
  exit
end
parser.on('-v', '--version', 'Print the version of webri.') do
  puts WebRI::VERSION
  exit
end
parser.separator(NAME)

parser.parse!

name = ARGV[0]
WebRI.new(name, options)
