#!/usr/bin/env ruby

# A console application to display Ruby HTML documentation.

require 'optparse'
require_relative '../lib/webri/version'
require_relative '../lib/webri'
require_relative '../lib/scraper'

NAME = <<-EOT
Name:


EOT
options = {}

parser = OptionParser.new

parser.version = WebRI::VERSION
parser.banner = <<-BANNER
webri is a console application for displaying Ruby online HTML documentation.
Documentation pages are opened in the default web browser.

Usage: #{parser.program_name} [options] name

BANNER

RELEASES = Scraper.scrapers.keys.inspect

parser.separator("Options:")
release_description = <<-EOT

EOT
parser.on('-r', '--release RELEASE',
          "Specify documentation release (one of #{RELEASES}).") do |value|
  options[:release_name] = value
end
parser.on('-i', '--info', 'Print information about webri.') do
  options[:info] = true
end
parser.on('--noreline', 'Do not use Reline (useful for testing).') do |value|
  options[:noreline] = true
end
parser.on('-n', '--noop', 'Do not actually open web pages.') do |value|
  options[:noop] = true
end
parser.on('-h', '--help', 'Print this help.') do
  puts parser
  exit
end
parser.on('-v', '--version', 'Print the version of webri.') do
  puts WebRI::VERSION
  exit
end
parser.separator(NAME)

parser.parse!

name = ARGV[0]
WebRI.new(name, options)
