#!/usr/bin/env ruby

# A console application to display Ruby HTML documentation.

require 'optparse'
require_relative '../lib/webri/version'
require_relative '../lib/webri'
require_relative '../lib/scraper'

NAME = <<EOT

Name:

There are four types of #{WebRI.variable('name')}, as determined by prefixes:

|------------------|----------------|--------------------|
|       Type       |   Starts With  |      Example       |
|------------------|----------------|--------------------|
| Class/module     | Capital letter | #{WebRI.tokenq('Array')}          |
| Singleton method | #{WebRI.tokenq('::')}           | #{WebRI.tokenq('::new')}            |
| Instance method  | #{WebRI.tokenq('#')}            | #{WebRI.tokenq('#inspect')}         |
| Ruby file        | #{WebRI.tokenq('ruby:')}        | #{WebRI.tokenq('ruby:syntax_rdoc')} |
|------------------|----------------|--------------------|

Note: Singleton method prefix should be escaped as #{WebRI.string('\\#')} if your shell requires it.

Name handling:

- If #{WebRI.variable('name')} is exactly a name of its type (but not the beginning of other such names),
  #{WebRI.webri} opens the page for that name.
  Examples: #{WebRI.tokenq('Array')}, #{WebRI.tokenq('::trap')}, #{WebRI.tokenq('#xmlschema')}, #{WebRI.tokenq('ruby:syntax_rdoc')}. 
- If #{WebRI.variable('name')} is the beginning of exactly one name of its type,
  #{WebRI.webri} asks whether to open the page for that name.
  Examples: #{WebRI.tokenq('Arra')}, #{WebRI.tokenq('::tra')}, #{WebRI.tokenq('#xmlschem')}, #{WebRI.tokenq('ruby:syntax_')}.
- If #{WebRI.variable('name')} is the beginning of multiple names of its type,
  #{WebRI.webri} displays those names and lets you choose.
  Examples: #{WebRI.tokenq('A')}, #{WebRI.tokenq('::t')}, #{WebRI.tokenq('#')}, #{WebRI.tokenq('ruby:s')}.
- If #{WebRI.variable('name')} is not a valid name of its type,
  #{WebRI.webri} asks whether show such names.
  Examples: #{WebRI.tokenq('Xyzzy')}, #{WebRI.tokenq('::xyzzy')}, #{WebRI.tokenq('#xyzzy')}, #{WebRI.tokenq('ruby:xyzzy')}.
- If #{WebRI.variable('name')} is not valid at all (i.e., does not start with any of the prefixes above),
  #{WebRI.webri} prints an error message.
  Examples: #{WebRI.tokenq('nosuch')}, #{WebRI.tokenq('$foo')}, #{WebRI.tokenq('%Bar')}.

EOT
options = {}

parser = OptionParser.new

parser.version = WebRI::VERSION
parser.banner = <<-BANNER
Console application #{WebRI.webri} displays Ruby online HTML documentation
in the default web browser.

Usage: #{WebRI.webri} [options] #{WebRI.variable('name')}

BANNER

RELEASES = Scraper.scrapers.keys.inspect

parser.separator("Options:")
release_description = <<-EOT

EOT
parser.on('-r', '--release RELEASE',
          "Specify documentation release (one of #{RELEASES}).") do |value|
  options[:release_name] = value
end
parser.on('-i', '--info', "Print information about #{WebRI.webri}.") do
  options[:info] = true
end
parser.on('--noreline', 'Do not use Reline (useful for testing).') do |value|
  options[:noreline] = true
end
parser.on('-n', '--noop', 'Do not actually open web pages.') do |value|
  options[:noop] = true
end
parser.on('-h', '--help', 'Print this help.') do
  puts parser
  exit
end
parser.on('-v', '--version', "Print the version of #{WebRI.webri}.") do
  puts WebRI::VERSION
  exit
end
parser.separator(NAME)

parser.parse!

name = ARGV[0]
WebRI.new(name, options)
